version: "2"

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    extends:
      file: docker-compose-base.yml
      service: postgres_config

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    extends:
      file: docker-compose-base.yml
      service: postgres_config
